name: Release Windows Assets

on:
  release:
    types: [ "published" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: lukka/get-cmake@latest

      - name: Install Dependencies
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Package
        working-directory: ${{github.workspace}}/build
        run: cpack -G "NSIS"

#      - name: Release
#        uses: softprops/action-gh-release@v2
#        with:
#          files: |
#            ${{github.workspace}}/build/Olympus-*-Linux.deb
#            ${{github.workspace}}/build/Olympus-*-Linux.zip
